Fix Routelistview
DeveloperAcademy-POSTECH/PickBus pull request #90
Opened 2022-12-10 13:12 UTC by gojeongseog

## 📣 Related Issue

- close #80 

## 🌁 Background

RouteListView 관련 이슈 해결

## 👩‍💻 Contents

RouteListView에서 정류장 Cell 눌렀을 때 앱 충돌
RouteListView 스와이프를 통한 삭제기능 없애기
RoteListView 도착정보 필터링 busId로 바꾸기
정류장 위치 라벨 추가
도착 예정 시간 60초 이하 곧도착으로 표시

## ✅ Testing

## 📱 Screenshot

![Simulator Screen Shot - iPhone 14 Pro - 2022-12-10 at 22 05 56](https://user-images.githubusercontent.com/94058164/206856897-32e55cc4-f20d-48ec-99c2-4f47ddf8503b.png)

## 📝 Review Note

## 📬 Reference

2022-12-10 14:08 UTC, shwoghk14 requested changes

2022-12-10 14:08 UTC, shwoghk14 commented on PickBus/Views/RouteListView/RouteListViewController.swift
> +                guard let myRoteId = busArray[nodeIndex][busIndex].routeId else { fatalError() }
```suggestion
                guard let myRoteId = busArray[nodeIndex][busIndex].routeId else { return }
```
해당 부분은 fatalError로 할 시, 리스트 들어가자 마자 정보 받아오는 중에 뒤로가기 누르면 앱이 꺼지는 현상이 발생합니다. return으로 해두면 앱이 꺼지지 않습니다.

2022-12-11 07:16 UTC, gojeongseog commented on PickBus/Views/RouteListView/RouteListViewController.swift
> +                guard let myRoteId = busArray[nodeIndex][busIndex].routeId else { fatalError() }
그렇군요! 해당 부분 확인해보고 수정하겠습니다

2022-12-11 08:09 UTC, gojeongseog commented on PickBus/Views/RouteListView/RouteListViewController.swift
> +                guard let myRoteId = busArray[nodeIndex][busIndex].routeId else { fatalError() }
수정했습니다!

2022-12-11 08:28 UTC, minjae9610 approved these changes
LGTM

2022-12-11 11:51 UTC, shwoghk14 approved these changes
좋습니다.

2022-12-11 13:35 UTC, HyeS00 approved these changes
LGTM

2022-12-11 14:23 UTC, merged